target:
	@javac ./StudentSocketImpl-skel.java
	@javac ./client0.java
	@javac ./client1.java
	@javac ./client2.java
	@javac ./client3.java
	@javac ./server0.java
	@javac ./server1.java
	@javac ./server2.java
	@javac ./server3.java
	

clean:
	$(RM) *.class
